import { Manrope } from "next/font/google";
import "./globals.css";


const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["400", "500", "600", "700","800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={` ${manrope.variable} h-full antialiased`}
    >
      <body className={`h-full bg-[#FDFDFB] ${manrope.className} bg-[#F9FAF2] min-h-screen flex flex-col`}>
        
        
        <main className="grow">
        {children}
        </main>
       
        </body>
    </html>
  );
}
